name: dahlia_backend
description: A starting point for Dart libraries or applications.
version: 0.0.1+1
homepage: https://dahliaos.io

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0-nullsafety.5
  path: ^1.7.0
  path_provider: any
  hive: ^2.0.0
  xdg_directories:
  cron: ^0.3.0
  intl: ^0.17.0-nullsafety.2
  crypto: any
  hive_flutter: any

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  vm_service: ^6.1.0+1
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - ../global/assets/