name: Submodule Updates

on:
  push:
  repository_dispatch:

jobs:
  Ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the main repo
        run: |
          curl -X POST https://api.github.com/repos/dahliaOS/pangolin_desktop/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "Update Submodules", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'